schema: ./generated/schema.graphql
extensions:
  endpoints:
    default:
      url: http://localhost:8080/v1/graphql
      headers:
        x-hasura-admin-secret: skfjngs78fgnj2lkwea8fu9ijekm_iujMcjwscHem3


# ${NEXT_PUBLIC_HASURA_ENDPOINT}